"""Generate a Flyway migration that refreshes districts from the cleaned LGD set (final.json)."""
import json, sys

d = json.load(open("final.json", encoding="utf8"))
out_path = sys.argv[1]
q = lambda s: "'" + s.replace("'", "''") + "'"
STATE_NAME = {s["code"]: s["name"] for s in d}

# (state code, old district, new district): districts renamed since the previous seed. Rebuild
# this list against whatever the previous migration seeded before generating a refresh.
REMAP = []
idx = {(s["code"], x["name"]) for s in d for x in s["districts"]}
for st, od, nd in REMAP:
    assert (st, nd) in idx, (st, nd)

L = []
w = L.append
w("""-- District refresh from the Local Government Directory (lgdirectory.gov.in). Generated by
-- backend/tools/lgd/gen_sql.py. Location is State -> District only (no city tier since V21).
""")
for table in ("profiles", "leagues", "grounds"):
    for st, od, nd in REMAP:
        w(f"UPDATE {table} SET district = {q(nd)} WHERE state = {q(STATE_NAME[st])} AND district = {q(od)};")
w("")
w("-- Upsert by LGD code so district ids (and anything pointing at them) survive the refresh.")
for s in d:
    w(f"-- {s['name']}")
    w("INSERT INTO districts (state_code, name, lgd_code) VALUES")
    w(",\n".join(f"    ({q(s['code'])}, {q(x['name'])}, {x['lgd']})" for x in s["districts"]))
    w("ON CONFLICT (lgd_code) DO UPDATE SET name = EXCLUDED.name, state_code = EXCLUDED.state_code;")
    w("")

open(out_path, "w", encoding="utf8", newline="\n").write("\n".join(L))
print("wrote", out_path, sum(len(s["districts"]) for s in d), "districts")
