-- District retrofit (see docs/PHASE1.md Section 6 "Retrofit: District tier" and
-- docs/PHASE2.md's Decisions Made): adds a real third location tier between State and
-- City -- State -> District -> City -- everywhere location is captured, profile included.
-- V4 already ran, so this is a pure additive/backfill migration, not an edit to V4.
--
-- Districts are genuine reference data, same posture as states/cities (V4's own doc
-- comment applies here too): not exhaustive, a curated set covering exactly the ~90
-- cities V4 already seeded, matching the same non-exhaustive scope rather than a
-- full India census-level district dataset.
CREATE TABLE districts (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    state_code  VARCHAR NOT NULL REFERENCES states(code) ON DELETE CASCADE,
    name        VARCHAR NOT NULL,
    UNIQUE (state_code, name)
);

INSERT INTO districts (state_code, name) VALUES
    ('AP', 'Guntur'), ('AP', 'Visakhapatnam'), ('AP', 'Krishna'), ('AP', 'Chittoor'),
    ('AR', 'Papum Pare'),
    ('AS', 'Kamrup Metropolitan'), ('AS', 'Cachar'), ('AS', 'Dibrugarh'),
    ('BR', 'Patna'), ('BR', 'Gaya'), ('BR', 'Bhagalpur'), ('BR', 'Muzaffarpur'),
    ('CG', 'Raipur'), ('CG', 'Bilaspur'), ('CG', 'Durg'),
    ('GA', 'North Goa'), ('GA', 'South Goa'),
    ('GJ', 'Gandhinagar'), ('GJ', 'Ahmedabad'), ('GJ', 'Surat'), ('GJ', 'Vadodara'), ('GJ', 'Rajkot'),
    ('HR', 'Gurugram'), ('HR', 'Faridabad'), ('HR', 'Panipat'), ('HR', 'Rohtak'),
    ('HP', 'Shimla'), ('HP', 'Kangra'),
    ('JH', 'Ranchi'), ('JH', 'East Singhbhum'), ('JH', 'Dhanbad'), ('JH', 'Bokaro'),
    ('KA', 'Bengaluru Urban'), ('KA', 'Mysuru'), ('KA', 'Dharwad'), ('KA', 'Dakshina Kannada'), ('KA', 'Belagavi'),
    ('KL', 'Thiruvananthapuram'), ('KL', 'Ernakulam'), ('KL', 'Kozhikode'), ('KL', 'Thrissur'),
    ('MP', 'Bhopal'), ('MP', 'Indore'), ('MP', 'Gwalior'), ('MP', 'Jabalpur'),
    ('MH', 'Mumbai City'), ('MH', 'Pune'), ('MH', 'Nagpur'), ('MH', 'Nashik'), ('MH', 'Thane'), ('MH', 'Aurangabad'),
    ('MN', 'Imphal West'),
    ('ML', 'East Khasi Hills'),
    ('MZ', 'Aizawl'),
    ('NL', 'Kohima'), ('NL', 'Dimapur'),
    ('OD', 'Khordha'), ('OD', 'Cuttack'), ('OD', 'Sundargarh'),
    ('PB', 'Amritsar'), ('PB', 'Ludhiana'), ('PB', 'Jalandhar'), ('PB', 'Patiala'),
    ('RJ', 'Jaipur'), ('RJ', 'Jodhpur'), ('RJ', 'Udaipur'), ('RJ', 'Kota'),
    ('SK', 'East Sikkim'),
    ('TN', 'Chennai'), ('TN', 'Coimbatore'), ('TN', 'Madurai'), ('TN', 'Tiruchirappalli'), ('TN', 'Salem'),
    ('TS', 'Hyderabad'), ('TS', 'Warangal Urban'), ('TS', 'Nizamabad'),
    ('TR', 'West Tripura'),
    ('UP', 'Lucknow'), ('UP', 'Kanpur Nagar'), ('UP', 'Varanasi'), ('UP', 'Agra'), ('UP', 'Gautam Buddh Nagar'), ('UP', 'Ghaziabad'), ('UP', 'Meerut'),
    ('UK', 'Dehradun'), ('UK', 'Haridwar'), ('UK', 'Nainital'),
    ('WB', 'Kolkata'), ('WB', 'Howrah'), ('WB', 'Darjeeling'), ('WB', 'Paschim Bardhaman'),
    ('AN', 'South Andaman'),
    ('CH', 'Chandigarh'),
    ('DN', 'Daman'), ('DN', 'Dadra and Nagar Haveli'),
    ('DL', 'New Delhi'),
    ('JK', 'Srinagar'), ('JK', 'Jammu'),
    ('LA', 'Leh'), ('LA', 'Kargil'),
    ('LD', 'Lakshadweep'),
    ('PY', 'Puducherry');

ALTER TABLE cities ADD COLUMN district_id UUID REFERENCES districts(id) ON DELETE CASCADE;

-- Backfill: assign each already-seeded city to its real district.
UPDATE cities c
SET district_id = d.id
FROM (VALUES
    ('AP', 'Amaravati', 'Guntur'),
    ('AP', 'Visakhapatnam', 'Visakhapatnam'),
    ('AP', 'Vijayawada', 'Krishna'),
    ('AP', 'Guntur', 'Guntur'),
    ('AP', 'Tirupati', 'Chittoor'),
    ('AR', 'Itanagar', 'Papum Pare'),
    ('AS', 'Guwahati', 'Kamrup Metropolitan'),
    ('AS', 'Dispur', 'Kamrup Metropolitan'),
    ('AS', 'Silchar', 'Cachar'),
    ('AS', 'Dibrugarh', 'Dibrugarh'),
    ('BR', 'Patna', 'Patna'),
    ('BR', 'Gaya', 'Gaya'),
    ('BR', 'Bhagalpur', 'Bhagalpur'),
    ('BR', 'Muzaffarpur', 'Muzaffarpur'),
    ('CG', 'Raipur', 'Raipur'),
    ('CG', 'Bilaspur', 'Bilaspur'),
    ('CG', 'Durg', 'Durg'),
    ('GA', 'Panaji', 'North Goa'),
    ('GA', 'Margao', 'South Goa'),
    ('GA', 'Vasco da Gama', 'South Goa'),
    ('GJ', 'Gandhinagar', 'Gandhinagar'),
    ('GJ', 'Ahmedabad', 'Ahmedabad'),
    ('GJ', 'Surat', 'Surat'),
    ('GJ', 'Vadodara', 'Vadodara'),
    ('GJ', 'Rajkot', 'Rajkot'),
    ('HR', 'Gurugram', 'Gurugram'),
    ('HR', 'Faridabad', 'Faridabad'),
    ('HR', 'Panipat', 'Panipat'),
    ('HR', 'Rohtak', 'Rohtak'),
    ('HP', 'Shimla', 'Shimla'),
    ('HP', 'Dharamshala', 'Kangra'),
    ('JH', 'Ranchi', 'Ranchi'),
    ('JH', 'Jamshedpur', 'East Singhbhum'),
    ('JH', 'Dhanbad', 'Dhanbad'),
    ('JH', 'Bokaro Steel City', 'Bokaro'),
    ('KA', 'Bengaluru', 'Bengaluru Urban'),
    ('KA', 'Mysuru', 'Mysuru'),
    ('KA', 'Hubballi', 'Dharwad'),
    ('KA', 'Mangaluru', 'Dakshina Kannada'),
    ('KA', 'Belagavi', 'Belagavi'),
    ('KL', 'Thiruvananthapuram', 'Thiruvananthapuram'),
    ('KL', 'Kochi', 'Ernakulam'),
    ('KL', 'Kozhikode', 'Kozhikode'),
    ('KL', 'Thrissur', 'Thrissur'),
    ('MP', 'Bhopal', 'Bhopal'),
    ('MP', 'Indore', 'Indore'),
    ('MP', 'Gwalior', 'Gwalior'),
    ('MP', 'Jabalpur', 'Jabalpur'),
    ('MH', 'Mumbai', 'Mumbai City'),
    ('MH', 'Pune', 'Pune'),
    ('MH', 'Nagpur', 'Nagpur'),
    ('MH', 'Nashik', 'Nashik'),
    ('MH', 'Thane', 'Thane'),
    ('MH', 'Aurangabad', 'Aurangabad'),
    ('MN', 'Imphal', 'Imphal West'),
    ('ML', 'Shillong', 'East Khasi Hills'),
    ('MZ', 'Aizawl', 'Aizawl'),
    ('NL', 'Kohima', 'Kohima'),
    ('NL', 'Dimapur', 'Dimapur'),
    ('OD', 'Bhubaneswar', 'Khordha'),
    ('OD', 'Cuttack', 'Cuttack'),
    ('OD', 'Rourkela', 'Sundargarh'),
    ('PB', 'Amritsar', 'Amritsar'),
    ('PB', 'Ludhiana', 'Ludhiana'),
    ('PB', 'Jalandhar', 'Jalandhar'),
    ('PB', 'Patiala', 'Patiala'),
    ('RJ', 'Jaipur', 'Jaipur'),
    ('RJ', 'Jodhpur', 'Jodhpur'),
    ('RJ', 'Udaipur', 'Udaipur'),
    ('RJ', 'Kota', 'Kota'),
    ('SK', 'Gangtok', 'East Sikkim'),
    ('TN', 'Chennai', 'Chennai'),
    ('TN', 'Coimbatore', 'Coimbatore'),
    ('TN', 'Madurai', 'Madurai'),
    ('TN', 'Tiruchirappalli', 'Tiruchirappalli'),
    ('TN', 'Salem', 'Salem'),
    ('TS', 'Hyderabad', 'Hyderabad'),
    ('TS', 'Warangal', 'Warangal Urban'),
    ('TS', 'Nizamabad', 'Nizamabad'),
    ('TR', 'Agartala', 'West Tripura'),
    ('UP', 'Lucknow', 'Lucknow'),
    ('UP', 'Kanpur', 'Kanpur Nagar'),
    ('UP', 'Varanasi', 'Varanasi'),
    ('UP', 'Agra', 'Agra'),
    ('UP', 'Noida', 'Gautam Buddh Nagar'),
    ('UP', 'Ghaziabad', 'Ghaziabad'),
    ('UP', 'Meerut', 'Meerut'),
    ('UK', 'Dehradun', 'Dehradun'),
    ('UK', 'Haridwar', 'Haridwar'),
    ('UK', 'Haldwani', 'Nainital'),
    ('WB', 'Kolkata', 'Kolkata'),
    ('WB', 'Howrah', 'Howrah'),
    ('WB', 'Siliguri', 'Darjeeling'),
    ('WB', 'Durgapur', 'Paschim Bardhaman'),
    ('AN', 'Port Blair', 'South Andaman'),
    ('CH', 'Chandigarh', 'Chandigarh'),
    ('DN', 'Daman', 'Daman'),
    ('DN', 'Silvassa', 'Dadra and Nagar Haveli'),
    ('DL', 'New Delhi', 'New Delhi'),
    ('JK', 'Srinagar', 'Srinagar'),
    ('JK', 'Jammu', 'Jammu'),
    ('LA', 'Leh', 'Leh'),
    ('LA', 'Kargil', 'Kargil'),
    ('LD', 'Kavaratti', 'Lakshadweep'),
    ('PY', 'Puducherry', 'Puducherry')
) AS mapping(state_code, city_name, district_name)
JOIN districts d ON d.state_code = mapping.state_code AND d.name = mapping.district_name
WHERE c.state_code = mapping.state_code AND c.name = mapping.city_name;

ALTER TABLE cities ALTER COLUMN district_id SET NOT NULL;
ALTER TABLE cities DROP CONSTRAINT cities_state_code_name_key;
ALTER TABLE cities DROP COLUMN state_code;
ALTER TABLE cities ADD CONSTRAINT cities_district_id_name_key UNIQUE (district_id, name);
